# ------------------------------------------------
# Case Name:
#       case_rfc2616_response-pragmaHead-multi-7Values
# Case Description:
#       cache MUST cache all values of a multi-valued Pragma response header with 7 values
# Testing Steps:
#       step 1: request 7 values Pragma response header
#       step 2: check whether the response be cached
# Author: qihai.qh@alibaba-inc.com
# -----------------------------------------------
# step 1: request 7 values Pragma response header
--- {
    Request: {
        method: GET,
        uri: '/pragmaHead-multi-7Values',
        protocol: HTTP/1.1,
        Connection: close,
        Host: "macaroon.zymlinux.net",
    },
    ServerCheck: {
        method: GET,
        uri: '/pragmaHead-multi-7Values',
        protocol: HTTP/1.1,
        Host: "macaroon.zymlinux.net",
    },
    Response: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Pragma: 'aa,bb,cc,dd,ee,ff,gg',
        Last-Modified: now-31536000,
        Cache-Control: 'max-age=10',
        Connection: close,
        body: body-pragma,
    },
    ClientCheck: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Last-Modified: now-31536000,
        Cache-Control: 'max-age=10',
        Pragma: 'aa,bb,cc,dd,ee,ff,gg',
        Connection: close,
        body: body-pragma,
    }
}

#step 2: check whether the response be cached
--- {
     Request: {
        uri: '/pragmaHead-multi-7Values',
        Host: "macaroon.zymlinux.net",
        Connection: close,
    },
    ClientCheck: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Last-Modified: now-31536000,
        Date: S_Date_Step1,
        Pragma: 'aa,bb,cc,dd,ee,ff,gg',
        body: body-pragma,
    }
}
