# ------------------------------------------------
# Case Name:
#       case_rfc2616_response-viaHead-multi-6Values
# Case Description:
#       cache MUST cache all values of a multi-valued Via response header with 6 values
# Testing Steps:
#       step 1: request 6 values Via response header
#       step 2: check whether the response be cached
# Author: qihai.qh@alibaba-inc.com
# -----------------------------------------------
# step 1: request 6 values Via response header
--- {
    Request: {
        method: GET,
        uri: '/viaHead-multi-6Values',
        protocol: HTTP/1.1,
        Connection: close,
        Host: "macaroon.alibaba.com",
    },
    ServerCheck: {
        method: GET,
        uri: '/viaHead-multi-6Values',
        protocol: HTTP/1.1,
        Host: "macaroon.alibaba.com",
    },
    Response: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Via: 'a1.1,b2.2,c3.3,d4.4,e5.5,f6.6',
        Last-Modified: now-31536000,
        Cache-Control: 'max-age=10',
        Connection: close,
        body: body-via,
    },
    ClientCheck: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Last-Modified: now-31536000,
        Cache-Control: 'max-age=10',
        Via: r"a1.1,b2.2,c3.3,d4.4,e5.5,f6.6",
       Connection: close,
       body: body-via,
    }
}

#step 2: check whether the response be cached
--- {
     Request: {
        uri: '/viaHead-multi-6Values',
        Host: "macaroon.alibaba.com",
        Connection: close,
    },
    ClientCheck: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Last-Modified: now-31536000,
        Date: S_Date_Step1,
        Via: r"a1.1,b2.2,c3.3,d4.4,e5.5,f6.6",
        body: body-via,
    }
}
