# ------------------------------------------------
# Case Name:
#       case_rfc2616_response-viaHead-order-multi-6Values
# Case Description:
#       cache MUST preserve field-value order when caching multi-valued Via response header with 6 values
# Testing Steps:
#       step 1: preserve field-value order when caching multi-valued Via response header with 6 values
# Author: qihai.qh@alibaba-inc.com
# -----------------------------------------------
# step 1: preserve field-value order when cacheing multi-valued Via response header with 6 values
--- {
    Request: {
        method: GET,
        uri: '/viaHead-order-multi-6Values',
        protocol: HTTP/1.1,
        Connection: close,
        Host: "macaroon.zymlinux.net",
    },
    ServerCheck: {
        method: GET,
        uri: '/viaHead-order-multi-6Values',
        protocol: HTTP/1.1,
        Host: "macaroon.zymlinux.net",
    },
    Response: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Via: 'a1.1,b2.2,c3.3,d4.4,e5.5,f6.6',
        Last-Modified: now-31536000,
        Connection: close,
        body: body-via,
    },
    ClientCheck: {
        protocol: HTTP/1.1,
        statuscode: 200,
        Last-Modified: now-31536000,
        Via: r"a1.1,b2.2,c3.3,d4.4,e5.5,f6.6",
       Connection: close,
       body: body-via,
    }
}
